export const AGENT_WALLET_ABI = [
  {
    name: 'owner',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'registry',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'agentId',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    name: 'usdc',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'dailyLimit',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'perTxLimit',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'dailySpent',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'windowStart',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'hasAllowlist',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'allowedRecipients',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'recipient', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'getNonce',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'isValidSignature',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'hash',      type: 'bytes32' },
      { name: 'signature', type: 'bytes'   },
    ],
    outputs: [{ name: '', type: 'bytes4' }],
  },
  {
    name: 'pay',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to',     type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'memo',   type: 'string'  },
    ],
    outputs: [],
  },
  {
    name: 'execute',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to',    type: 'address' },
      { name: 'value', type: 'uint256' },
      { name: 'data',  type: 'bytes'   },
    ],
    outputs: [],
  },
  {
    name: 'executeBatch',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'targets', type: 'address[]' },
      { name: 'values',  type: 'uint256[]' },
      { name: 'datas',   type: 'bytes[]'   },
    ],
    outputs: [],
  },
  {
    name: 'updateLimits',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: '_dailyLimit', type: 'uint256' },
      { name: '_perTxLimit', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    name: 'allowRecipient',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'recipient', type: 'address' }],
    outputs: [],
  },
  {
    name: 'blockRecipient',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'recipient', type: 'address' }],
    outputs: [],
  },
  {
    name: 'disableAllowlist',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'withdrawETH',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to',     type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    name: 'PaymentSent',
    type: 'event',
    inputs: [
      { name: 'to',      type: 'address', indexed: true  },
      { name: 'amount',  type: 'uint256', indexed: false },
      { name: 'memo',    type: 'string',  indexed: false },
      { name: 'logHash', type: 'bytes32', indexed: false },
    ],
  },
  {
    name: 'LimitsUpdated',
    type: 'event',
    inputs: [
      { name: 'dailyLimit', type: 'uint256', indexed: false },
      { name: 'perTxLimit', type: 'uint256', indexed: false },
    ],
  },
  {
    name: 'RecipientAllowed',
    type: 'event',
    inputs: [{ name: 'recipient', type: 'address', indexed: true }],
  },
  {
    name: 'RecipientBlocked',
    type: 'event',
    inputs: [{ name: 'recipient', type: 'address', indexed: true }],
  },
  {
    name: 'AllowlistEnabled',
    type: 'event',
    inputs: [],
  },
  {
    name: 'AllowlistDisabled',
    type: 'event',
    inputs: [],
  },
] as const

export const AGENT_REGISTRY_ABI = [
  {
    name: 'getAgent',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'agentId', type: 'bytes32' }],
    outputs: [{
      type: 'tuple',
      components: [
        { name: 'wallet',          type: 'address' },
        { name: 'operator',        type: 'address' },
        { name: 'manifestHash',    type: 'bytes32' },
        { name: 'registeredAt',    type: 'uint64'  },
        { name: 'lastActiveAt',    type: 'uint64'  },
        { name: 'executionCount',  type: 'uint32'  },
        { name: 'totalSettled',    type: 'uint128' },
        { name: 'reputationScore', type: 'uint16'  },
        { name: 'status',          type: 'uint8'   },
      ],
    }],
  },
  {
    name: 'isActive',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'agentId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'getWallet',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'agentId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'getOperator',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'agentId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'getAgentsByOperator',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'operator', type: 'address' }],
    outputs: [{ name: '', type: 'bytes32[]' }],
  },
  {
    name: 'trustedFactories',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'factory', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'owner',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'registerAgent',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'agentId',      type: 'bytes32' },
      { name: 'wallet',       type: 'address' },
      { name: 'operator',     type: 'address' },
      { name: 'manifestHash', type: 'bytes32' },
    ],
    outputs: [],
  },
  {
    name: 'pauseAgent',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'agentId', type: 'bytes32' }],
    outputs: [],
  },
  {
    name: 'resumeAgent',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'agentId', type: 'bytes32' }],
    outputs: [],
  },
  {
    name: 'revokeAgent',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'agentId', type: 'bytes32' }],
    outputs: [],
  },
  {
    name: 'updateManifest',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'agentId',         type: 'bytes32' },
      { name: 'newManifestHash', type: 'bytes32' },
    ],
    outputs: [],
  },
  {
    name: 'logExecution',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'agentId',       type: 'bytes32' },
      { name: 'logHash',       type: 'bytes32' },
      { name: 'amountSettled', type: 'uint256' },
      { name: 'success',       type: 'bool'    },
    ],
    outputs: [],
  },
  {
    name: 'addFactory',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'factory', type: 'address' }],
    outputs: [],
  },
  {
    name: 'AgentRegistered',
    type: 'event',
    inputs: [
      { name: 'agentId',      type: 'bytes32', indexed: true  },
      { name: 'wallet',       type: 'address', indexed: true  },
      { name: 'operator',     type: 'address', indexed: true  },
      { name: 'manifestHash', type: 'bytes32', indexed: false },
    ],
  },
  {
    name: 'AgentPaused',
    type: 'event',
    inputs: [
      { name: 'agentId', type: 'bytes32', indexed: true },
      { name: 'by',      type: 'address', indexed: true },
    ],
  },
  {
    name: 'AgentResumed',
    type: 'event',
    inputs: [
      { name: 'agentId', type: 'bytes32', indexed: true },
      { name: 'by',      type: 'address', indexed: true },
    ],
  },
  {
    name: 'AgentRevoked',
    type: 'event',
    inputs: [
      { name: 'agentId', type: 'bytes32', indexed: true },
      { name: 'by',      type: 'address', indexed: true },
    ],
  },
  {
    name: 'ManifestUpdated',
    type: 'event',
    inputs: [
      { name: 'agentId', type: 'bytes32', indexed: true  },
      { name: 'oldHash', type: 'bytes32', indexed: false },
      { name: 'newHash', type: 'bytes32', indexed: false },
    ],
  },
  {
    name: 'ExecutionLogged',
    type: 'event',
    inputs: [
      { name: 'agentId',       type: 'bytes32', indexed: true  },
      { name: 'logHash',       type: 'bytes32', indexed: true  },
      { name: 'amountSettled', type: 'uint256', indexed: false },
      { name: 'success',       type: 'bool',    indexed: false },
    ],
  },
  {
    name: 'ReputationUpdated',
    type: 'event',
    inputs: [
      { name: 'agentId',  type: 'bytes32', indexed: true  },
      { name: 'oldScore', type: 'uint16',  indexed: false },
      { name: 'newScore', type: 'uint16',  indexed: false },
    ],
  },
] as const

export const AGENT_WALLET_FACTORY_ABI = [
  {
    name: 'implementation',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'registry',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'usdc',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'wallets',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'agentId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'getWalletAddress',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'agentId', type: 'bytes32' },
      { name: 'owner',   type: 'address' },
    ],
    outputs: [{ name: 'predicted', type: 'address' }],
  },
  {
    name: 'createWallet',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'agentId',      type: 'bytes32' },
      { name: 'owner',        type: 'address' },
      { name: 'dailyLimit',   type: 'uint256' },
      { name: 'perTxLimit',   type: 'uint256' },
      { name: 'manifestHash', type: 'bytes32' },
    ],
    outputs: [{ name: 'wallet', type: 'address' }],
  },
  {
    name: 'WalletCreated',
    type: 'event',
    inputs: [
      { name: 'agentId',    type: 'bytes32', indexed: true  },
      { name: 'wallet',     type: 'address', indexed: true  },
      { name: 'operator',   type: 'address', indexed: true  },
      { name: 'dailyLimit', type: 'uint256', indexed: false },
      { name: 'perTxLimit', type: 'uint256', indexed: false },
    ],
  },
] as const

export const ERC20_ABI = [
  {
    name: 'balanceOf',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'transfer',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to',     type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'decimals',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    name: 'approve',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount',  type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'allowance',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'owner',   type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
] as const
