// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Script, console2} from "forge-std/Script.sol";
import {AgentWallet}        from "../src/AgentWallet.sol";
import {AgentRegistry}      from "../src/AgentRegistry.sol";
import {AgentWalletFactory} from "../src/AgentWalletFactory.sol";

/**
 * @title  Deploy
 * @notice Deploys the full Actant contract suite and wires everything up atomically.
 *
 *  Deployment order (must be sequential — registry is needed by factory):
 *  1. AgentWallet implementation — the logic contract all proxies point to
 *  2. AgentRegistry             — ERC-8004 identity and reputation store
 *  3. AgentWalletFactory        — deploys proxies and registers them in one tx
 *  4. registry.addFactory()     — authorize the factory to register agents
 *  
 *  Output:
 *    Writes addresses to deployment.env (gitignored) for easy copy-paste.
 */
contract Deploy is Script {

    // ------------------------------------------------------------
    //                       USDC Addresses
    // ------------------------------------------------------------

    address constant USDC_BASE_MAINNET = 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913;
    address constant USDC_BASE_SEPOLIA = 0x036CbD53842c5426634e7929541eC2318f3dCF7e;

    // ------------------------------------------------------------
    //                           Run
    // ------------------------------------------------------------

    function run() external {
        uint256 deployerKey = vm.envOr("PRIVATE_KEY", uint256(0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80));
        address deployer    = vm.addr(deployerKey);

        uint256 chainId = block.chainid;
        address usdc    = chainId == 8453 ? USDC_BASE_MAINNET : USDC_BASE_SEPOLIA;

        console2.log("=== Actant Deployment ===");
        console2.log("Chain:    ", chainId);
        console2.log("Network:  ", chainId == 8453 ? "Base Mainnet" : "Base Sepolia");
        console2.log("Deployer: ", deployer);
        console2.log("USDC:     ", usdc);
        console2.log("");

        vm.startBroadcast(deployerKey);

        // 1. Deploy AgentWallet implementation
        AgentWallet impl = new AgentWallet();

        // 2. Deploy AgentRegistry (ERC-8004 identity + reputation)
        AgentRegistry registry = new AgentRegistry();

        // 3. Deploy AgentWalletFactory (links to impl + registry + USDC)
        AgentWalletFactory factory = new AgentWalletFactory(
            address(impl),
            address(registry),
            usdc
        );

        // 4. Authorize factory to register agents without operator being msg.sender
        registry.addFactory(address(factory));

        vm.stopBroadcast();

        // ── Output ──────────────────────────────────────────────────────────
        console2.log("=== Deployed ===");
        console2.log("AgentWallet impl:  ", address(impl));
        console2.log("AgentRegistry:     ", address(registry));
        console2.log("AgentWalletFactory:", address(factory));
        console2.log("");

        string memory explorer = chainId == 8453
            ? "https://basescan.org/address/"
            : "https://sepolia.basescan.org/address/";

        console2.log("=== Explorer ===");
        console2.log(string.concat("Registry: ", explorer, vm.toString(address(registry))));
        console2.log(string.concat("Factory:  ", explorer, vm.toString(address(factory))));
        console2.log("");

        // Write .env snippet for easy copy-paste into dashboard/.env.local
        string memory envOut = string.concat(
            "# Auto-generated by forge script/Deploy.s.sol\n",
            "# Copy these into dashboard/.env.local\n\n",
            "REGISTRY_ADDRESS=",                   vm.toString(address(registry)), "\n",
            "FACTORY_ADDRESS=",                    vm.toString(address(factory)),  "\n",
            "NEXT_PUBLIC_REGISTRY_ADDRESS=",       vm.toString(address(registry)), "\n",
            "NEXT_PUBLIC_FACTORY_ADDRESS=",        vm.toString(address(factory)),  "\n",
            "NEXT_PUBLIC_CHAIN_ID=",               vm.toString(chainId),           "\n"
        );

        vm.writeFile("deployment.env", envOut);
        console2.log("Addresses saved to: packages/contracts/deployment.env");
    }
}
