export const AGENT_REGISTRY_ABI = [
  {
    name: 'getAgent',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'agentId', type: 'bytes32' }],
    outputs: [{
      type: 'tuple',
      components: [
        { name: 'wallet',          type: 'address' },
        { name: 'operator',        type: 'address' },
        { name: 'manifestHash',    type: 'bytes32' },
        { name: 'registeredAt',    type: 'uint64'  },
        { name: 'lastActiveAt',    type: 'uint64'  },
        { name: 'executionCount',  type: 'uint32'  },
        { name: 'totalSettled',    type: 'uint128' },
        { name: 'reputationScore', type: 'uint16'  },
        { name: 'status',          type: 'uint8'   },
      ],
    }],
  },
  {
    name: 'isActive',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'agentId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'getWallet',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'agentId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'getOperator',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'agentId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'getAgentsByOperator',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'operator', type: 'address' }],
    outputs: [{ name: '', type: 'bytes32[]' }],
  },
  {
    name: 'trustedFactories',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'factory', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'owner',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'registerAgent',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'agentId',      type: 'bytes32' },
      { name: 'wallet',       type: 'address' },
      { name: 'operator',     type: 'address' },
      { name: 'manifestHash', type: 'bytes32' },
    ],
    outputs: [],
  },
  {
    name: 'pauseAgent',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'agentId', type: 'bytes32' }],
    outputs: [],
  },
  {
    name: 'resumeAgent',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'agentId', type: 'bytes32' }],
    outputs: [],
  },
  {
    name: 'revokeAgent',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'agentId', type: 'bytes32' }],
    outputs: [],
  },
  {
    name: 'updateManifest',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'agentId',         type: 'bytes32' },
      { name: 'newManifestHash', type: 'bytes32' },
    ],
    outputs: [],
  },
  {
    name: 'logExecution',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'agentId',       type: 'bytes32' },
      { name: 'logHash',       type: 'bytes32' },
      { name: 'amountSettled', type: 'uint256' },
      { name: 'success',       type: 'bool'    },
    ],
    outputs: [],
  },
  {
    name: 'addFactory',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'factory', type: 'address' }],
    outputs: [],
  },
  {
    name: 'AgentRegistered',
    type: 'event',
    inputs: [
      { name: 'agentId',      type: 'bytes32', indexed: true  },
      { name: 'wallet',       type: 'address', indexed: true  },
      { name: 'operator',     type: 'address', indexed: true  },
      { name: 'manifestHash', type: 'bytes32', indexed: false },
    ],
  },
  {
    name: 'AgentPaused',
    type: 'event',
    inputs: [
      { name: 'agentId', type: 'bytes32', indexed: true },
      { name: 'by',      type: 'address', indexed: true },
    ],
  },
  {
    name: 'AgentResumed',
    type: 'event',
    inputs: [
      { name: 'agentId', type: 'bytes32', indexed: true },
      { name: 'by',      type: 'address', indexed: true },
    ],
  },
  {
    name: 'AgentRevoked',
    type: 'event',
    inputs: [
      { name: 'agentId', type: 'bytes32', indexed: true },
      { name: 'by',      type: 'address', indexed: true },
    ],
  },
  {
    name: 'ManifestUpdated',
    type: 'event',
    inputs: [
      { name: 'agentId', type: 'bytes32', indexed: true  },
      { name: 'oldHash', type: 'bytes32', indexed: false },
      { name: 'newHash', type: 'bytes32', indexed: false },
    ],
  },
  {
    name: 'ExecutionLogged',
    type: 'event',
    inputs: [
      { name: 'agentId',       type: 'bytes32', indexed: true  },
      { name: 'logHash',       type: 'bytes32', indexed: true  },
      { name: 'amountSettled', type: 'uint256', indexed: false },
      { name: 'success',       type: 'bool',    indexed: false },
    ],
  },
  {
    name: 'ReputationUpdated',
    type: 'event',
    inputs: [
      { name: 'agentId',  type: 'bytes32', indexed: true  },
      { name: 'oldScore', type: 'uint16',  indexed: false },
      { name: 'newScore', type: 'uint16',  indexed: false },
    ],
  },
] as const

