export const AGENT_WALLET_ABI = [
  {
    name: 'owner',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'registry',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'agentId',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    name: 'usdc',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    name: 'dailyLimit',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'perTxLimit',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'dailySpent',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'windowStart',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'hasAllowlist',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'allowedRecipients',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'recipient', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    name: 'getNonce',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'isValidSignature',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'hash',      type: 'bytes32' },
      { name: 'signature', type: 'bytes'   },
    ],
    outputs: [{ name: '', type: 'bytes4' }],
  },
  {
    name: 'pay',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to',     type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'memo',   type: 'string'  },
    ],
    outputs: [],
  },
  {
    name: 'execute',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to',    type: 'address' },
      { name: 'value', type: 'uint256' },
      { name: 'data',  type: 'bytes'   },
    ],
    outputs: [],
  },
  {
    name: 'executeBatch',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'targets', type: 'address[]' },
      { name: 'values',  type: 'uint256[]' },
      { name: 'datas',   type: 'bytes[]'   },
    ],
    outputs: [],
  },
  {
    name: 'updateLimits',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: '_dailyLimit', type: 'uint256' },
      { name: '_perTxLimit', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    name: 'allowRecipient',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'recipient', type: 'address' }],
    outputs: [],
  },
  {
    name: 'blockRecipient',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'recipient', type: 'address' }],
    outputs: [],
  },
  {
    name: 'disableAllowlist',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'withdrawETH',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to',     type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    name: 'PaymentSent',
    type: 'event',
    inputs: [
      { name: 'to',      type: 'address', indexed: true  },
      { name: 'amount',  type: 'uint256', indexed: false },
      { name: 'memo',    type: 'string',  indexed: false },
      { name: 'logHash', type: 'bytes32', indexed: false },
    ],
  },
  {
    name: 'LimitsUpdated',
    type: 'event',
    inputs: [
      { name: 'dailyLimit', type: 'uint256', indexed: false },
      { name: 'perTxLimit', type: 'uint256', indexed: false },
    ],
  },
  {
    name: 'RecipientAllowed',
    type: 'event',
    inputs: [{ name: 'recipient', type: 'address', indexed: true }],
  },
  {
    name: 'RecipientBlocked',
    type: 'event',
    inputs: [{ name: 'recipient', type: 'address', indexed: true }],
  },
  {
    name: 'AllowlistEnabled',
    type: 'event',
    inputs: [],
  },
  {
    name: 'AllowlistDisabled',
    type: 'event',
    inputs: [],
  },
] as const

